// Themes
export { THEME_MAP, THEMES } from './themes';

// Texts
export { ALL_TEXTS } from './texts';

// Languages
export { LANGUAGES } from './languages';

// Configuration & Platform
export {
  PLATFORMS,
  DELETE_INST_NAME,
  URL_REGEX,
  WRITING_DEBOUNCE_TIMEOUT,
  DELETE_INSTRUCTION_DEBOUNCE_TIMEOUT,
  GREETING_TEXT_REQ_DEBOUNCE_TIMEOUT,
  EU_PROVIDER_URL,
  EU_PROVIDER_API_URL,
  WHATS_NEW_MODAL_LCST_FLAG
} from './config';

// Wizard & Steps
export {
  STEPS,
  TAB_STEPS,
  PROMPTS,
  STEP_TO_BUILDER_PATH
} from './wizard';

// Agent
export {
  CHATTINESS_LEVELS,
  TONE_OF_VOICES,
  TRAIN_TYPES,
  MATERIAL_STATUS,
  GREETING_MESSAGE,
  CUSTOMIZATION_KEYS,
  THEME_CUSTOMIZATION_KEYS,
  FONTS,
  DEVICES,
  VERBAL_TOGGLE,
  POSITION,
  AUTO_OPEN_CHAT_VALUES,
  OPEN_BY_DEFAULT_OPTIONS,
  VISIBILITY_LAYOUT,
  KEY_KEYCODE_LIST,
  WOO_COMMERCE_PROPERTIES
} from './agent';

// Page Selection
export {
  SELECTION_TYPE_LABELS,
  SELECTION_TYPE_VALUES,
  SELECTION_OPTIONS,
  URL_MATCH_TYPE_LABELS,
  URL_MATCH_TYPE_VALUES,
  URL_MATCH_OPTIONS,
  VISIBILITY_TOGGLE,
  DUMMY_AVAILABLE_PAGES
} from './pageSelection';

export const AVATAR_VIEW_MODE = {
  LIST: 'list',
  CUSTOM: 'custom'
};
