export const ALL_TEXTS = {
  LETS_START: 'Let\'s start',
  BACK: 'Back',
  NEXT: 'Next',
  READ_TO_BUILD_YOUR_AI: 'Ready to build your AI Chatbot?',
  CREATE_AND_CUSTOMIZE_YOUR_AI: 'Create and customize your AI Chatbot in minutes',

  SETUP_YOUR_AI_CHATBOT: 'Setup Your AI Chatbot',
  USE_TEMPLATE_READY_OR_START_FROM_SCRATCH: 'You can use our ready-to-use prompts or start from scratch.',
  GREETING: 'Greeting',
  SHOW_A_MESSAGE: 'Show a message to greet users',
  HOW_CAN_I_HELP_YOU: 'Hi! How can I help you?',
  PULSING: 'Pulsing',
  ADD_A_PULSE_EFFECT: 'Add a pulsing effect to the avatar',
  POSITION: 'Position',
  LEFT: 'Left',
  RIGHT: 'Right',
  CHOOSE_THE_AI_AGENT: 'Choose the AI Agent\'s screen position',

  COLOR_SCHEME: 'COLOR SCHEME',
  AGENT_BACKGROUND_STYLE: 'AGENT BACKGROUND STYLE',
  START_COLOR: 'Start Color',
  END_COLOR: 'End Color',
  CHAT_STYLE: 'CHAT STYLE',
  CHAT_BACKGROUND_COLOR: 'Chat Background Color',
  FONT_FAMILY: 'Font Family',
  FONT_COLOR: 'Font Color',
  CHAT_THEME_COLOR: 'Chat Theme Color',
  BUTTON_STYLE: 'BUTTON STYLE',
  BUTTON_COLOR: 'Button Color',
  ICON_COLOR: 'Icon Color',
  DEFAULT: 'Default',
  MINIMAL: 'Minimal',
  CREATE_AI_CHATBOT: 'Create AI Chatbot',
  CREATE: 'Create',

  DESCRIBE_THE_AGENT_YOU_WANT_TO_CREATE: 'Describe the agent you want to create',
  EXAMPLE_PROVIDE_CUSTOMER_SUPPORT_BY_ANSWERING_FAQS_AND_GUIDING_USERS_THROUGH: 'Example: Provide customer support by answering FAQs and guiding users through troubleshooting steps.',
  FEEDBACK: 'Feedback',
  SHOW_AI_CHATBOT_ON: 'Show AI Chatbot on',
  CHOOSE_PAGES_THE_AI_CHATBOT_WILL_BE_SHOWN_ON: 'Choose pages the AI Chatbot will be shown on.',

  VIEW_CONVERSATIONS: 'View Conversations',

  GIVE_FEEDBACK: 'Give Feedback',

  REMOVE_CHATBOT_FROM_WEBSITE: 'Remove Chatbot from Website?',
  // eslint-disable-next-line max-len
  CLICK_REMOVE_FROM_WEBSITE_TO_PERMANENTLY_DELETE: 'Click Remove from Website to permanently delete this chatbot’s site-specific settings and remove it from your website.',
  YOUR_CHATBOT_AND_ITS_TRANING_DATA_WILL_STILL_BE_SAVED: 'Your chatbot and its training data will still be saved, but you’ll need to configure site-specific settings again if you add it back.',
  UNPUBLISH_CHATBOT_FROM_WEBSITE: 'Unpublish Chatbot from Website?',
  // eslint-disable-next-line max-len
  CLICK_UNPUBLISH_TO_REMOVE_THE_CHATBOT: 'Click Unpublish to remove the chatbot from your website while keeping its site-specific settings saved. You can republish it later without losing your setup.',
  YOUR_CHATBOT_AND_ITS_TRANING_DATA_WILL_REMAIN_SAVED: 'Your chatbot and its training data will remain saved.',

  OPEN_A_SUPPORT_TICKET: 'Open a Support Ticket',
  YOU_WILL_BE_REDIRECTED_TO_SUPPORT: 'You’ll be redirected to the Jotform AI Chatbot support page on WordPress.org.',
  TO_SUBMIT_A_TICKET_PLEASE: 'To submit a ticket, please make sure you’re [1[logged in]] or [2[create a free WordPress.org account.]]',

  UNPUBLISH: 'Unpublish',
  UNPUBLISHING: 'Unpublishing...',

  REMOVE_FROM_WEBSITE: 'Remove from Website',
  REMOVE_FROM_WEBSITE_2: 'Remove from website',
  REMOVING: 'Removing...',

  ANIMATION_TITLE: 'Chatbot Introduction Animation',

  AGENT_AVATAR: 'Agent Avatar',
  SELECT_AN_AVATAR: 'Select an avatar for your agent.',
  AI_PERSONA: 'AI Persona',

  CURRENT_AVATAR: 'Current Avatar',

  AGENT_NAME: 'Agent Name',
  GIVE_A_NAME_TO_YOUR_AGENT_THAT_WILL_BE_DISPLAYED_IN_THE_CONVERSATION: 'Give a name to your agent that will be displayed in the conversation',
  AGENT_ROLE: 'Agent Role',
  DESCRIPTION_YOUR_AGENTS_JOB_TITLE: 'Describe your agent’s job title',
  CHATTINESS: 'Chattiness',
  SPECIFY_THE_DESIRED_LEVEL_OF_DETAIL_IN_THE_AGENTS_RESPONSES: 'Specify the desired level of detail in the agent\'s responses',
  GO_TO_PRICING: 'Go to Pricing',
  YOU_HAVE_REACHED_YOUR_LIMIT: 'You\'ve reached your AI Chatbot limit.',
  DELETE_EXISTING_AGENT: 'Delete an existing agent or upgrade to add more.',

  DESCRIBE: 'Describe',
  SELECT_FROM_AGENTS: 'Select from My AI Agents',
  DEFAULT_LANGUAGE: 'Default Language',
  SELECT_THE_LANGUAGE: 'Select the language in which your agents greet users',
  TONE_OF_VOICE: 'Tone of Voice',
  SELECT_HOW_TO_COMMUNICATE: 'Select how you would like the AI to communicate',

  HOW_TO_USE_JOTFORM_AI_CHATBOT: 'How to use Jotform AI Chatbot?',
  AGENT_STYLE: 'Agent style',
  VISIBILITY: 'Visibility',
  KNOWLEDGE_BASE: 'Knowledge base',
  GREETING_MESSAGE: 'Greeting Message',
  SHOW_A_MESSAGE_TO_GREET_USERS: 'Show a message to greet users',
  CHAT_GUIDELINES: 'Chat Guidelines',
  SET_CLEAR_RULES: 'Set clear rules for how your agent should respond in chat channels',
  ADD_NEW: 'Add New',
  VISIBLE_ON: 'Visible on',
  CHOOSE_WHERE_THE_CHATBOT_SHOULD_APPEAR: 'Choose where the chatbot should appear',
  OPEN_BY_DEFAULT: 'Open by default',
  CHOOSE_WHEN_CHATBOT_WILL_APPEAR: 'Choose when chatbot will appear',
  ADVANCED_VISIBILITY: 'Advanced Visibility',
  CHOOSE_WHERE_CHATBOT_WILL_BE_SHOWN_OR_HIDDEN: 'Choose where chatbot will be shown or hidden',
  SHOW_ON: 'Show on',
  HIDE_ON: 'Hide on',
  DO_NOT_OPEN_AUTOMATICALLY: 'Do not open automatically',
  ALWAYS_OPEN: 'Always open',
  OPEN_AFTER_FIVE_SECONDS: 'Open after 5 seconds',
  OPEN_AFTER_TEN_SECONDS: 'Open after 10 seconds',
  DO_YOU_WANT_TO_DELETE_INSTRUCTION: 'Do you want to delete this instruction?',
  THIS_INSTRUCTION_WILL_BE_REMOVED_PERMANENTLY: 'This instruction will be removed permanently.',
  NO_KEEP: 'No, keep',
  YES_DELETE: 'Yes, delete',
  ADD: 'Add',
  ENTER_URL: 'Enter URL',
  URL: 'URL',
  REMOVE_AI_CHATBOT_FROM_MY_WEBSITE: 'Remove AI Chatbot from My Website',
  ANONYMOUS: 'Anonymous',
  CONVERSATIONS: 'Conversations',
  SEE_CONVERSATIONS_ON_JOTFORM: 'See conversation on Jotform',
  GO_TO_JOTFORM: 'Go to Jotform',
  PREVIEW: 'Preview',
  PUBLISH: 'Publish',
  PUBLISHED: 'Published',
  AUTO_TRAINED_KNOWLEDGE: 'Auto-trained knowledge',
  // eslint-disable-next-line max-len
  YOUR_AI_CHATBOT_IS_AUTOMATICALLY_TRAINED: 'Your AI chatbot is automatically trained with your website\'s content, such as pages, posts, and more, to provide a smarter, more relevant experience for your users.',
  CONVERSATIONS_WILL_BE_LISTED_HERE: 'Conversations will be listed here',
  YOU_DONT_HAVE_ANY_CONVERSATIONS: 'You don\'t have any conversations',
  CONTINUE: 'Continue',
  YOUR_AI_CHATBOT_WILL_BE_LIVE_ON_ALL_PAGES: 'Your AI chatbot will be live on all pages once published.',
  YOUR_AI_CHATBOT_IS_CURRENTLY_LIVE_ON_ALL_PAGES: 'Your AI chatbot is currently live on all pages.',
  LAYOUT: 'Layout',
  EXTENDED: 'Extended',
  CHOOSE_HOW_CHATBOT_APPEARS: 'Choose how the chatbot appears on your website',

  WHATS_NEW: 'What’s new 🔥',
  GET_THE_LATEST_CHANGES_AND_UPDATES: 'Get the latest changes and updates',
  TRY_IT_NOW: 'Try it now',
  SETTINGS: 'Settings',
  GENERAL: 'General',
  AGENT_SKILLS: 'Agent Skills',
  WOO_COMMERCE: 'WooCommerce',
  WOOCOMMERCE_STORE_SETTINGS: 'WOOCOMMERCE STORE SETTINGS',
  CONSUMER_KEY: 'Consumer Key',
  YOUR_WOO_COMMERCE_API_KEY: 'Your WooCommerce API key used to connect the store.',
  CONSUMER_SECRET: 'Consumer Secret',
  YOUR_WOO_COMMERCE_API_SECRET: 'Your WooCommerce API secret for secure access.',
  FIND_PRODUCTS: 'Find Products',
  HELPS_CUSTOMERS_SEARCH_OR_FILTER_PRODUCTS: 'Helps customers search or filter products by attributes such as price, size, or color.',
  RECOMMEND_PRODUCTS: 'Recommend Products',
  SUGGESTS_BEST_SELLERS: 'Suggests best sellers, trending items, or personalized recommendations to guide customer choices.',
  ADD_PRODUCTS_TO_CART: 'Add Products to Cart',
  ADD_ITEMS_TO_THE_SHOPPING_CART: ' Adds items to the shopping cart based on customer requests.',
  SHOW_ORDER_STATUS: 'Show Order Status',
  PRODVIDES_REAL_TIME_UPDATES: 'Provides real-time updates so customers can track their orders with ease. ',
  MANAGE_REFUNDS: 'Manage Refunds',
  HANDLE_REFUND_REQUESTS: 'Handle customer refund requests, approve or decline them, and share status updates.',
  CONNECT: 'Connect Store',
  KEY_PLACEHOLDER: 'Please enter your key here',
  SECRET_PLACEHOLDER: 'Please enter your secret here',
  CHATBOT_ABILITIES: 'CHATBOT ABILITIES',
  COMING_SOON: 'Coming Soon',
  DISCONNECT_STORE: 'Disconnect Store',
  UPGRADE_PLAN: 'Upgrade Plan',
  PUBLISHING: 'Publishing...',
  CANCEL: 'Cancel',
  CONNECTED_CHATBOT: 'Connected Chatbot',
  CONNECTED_JOTFORM_ACCOUNT: 'Connected Jotform Account',
  LOGOUT: 'Logout',
  LOGGINGOUT: 'Logging out...',
  LOGOUT_DIALOG_TITLE: 'Log Out from Your Account?',
  LOGOUT_DIALOG_DESC: 'Click Logout to sign out of your account. Your settings and preferences will remain saved, and you can log back in anytime without losing your setup.',
  LOGOUT_DIALOG_INFO: 'All your data and saved progress will remain secure.',
  CONNECTED_STORE: 'Connected Store',
  // eslint-disable-next-line max-len
  NETWORK_ERROR_DESC_ENTERPRISE: 'Unable to connect to the server. Please check your internet connection and try again. If you’re using an enterprise account, contact your system administrator for assistance.',
  UNAUTHORIZED_API_KEY_DESC: 'You don’t have permission to use this plugin. Please contact your system administrator to enable access.',

  WOOCOMMERCE_PLUGIN_NOT_INSTALLED: 'To use this feature, please make sure the [1[WooCommerce plugin is installed and active]] on your site.',
  WOOCOMMERCE_CONSUMER_SECRET_AND_KEY: 'You can create your Consumer Secret and Key in [1[WooCommerce > Settings > Advanced > REST API.]]',
  WOOCOMMERCE_PERMALINK_ERROR: 'Your site is using [1[Plain permalinks]], which prevents the integration from working. Please update your permalink settings [2[here.]]',
  INVALID_CREDENTIALS: 'Connection failed - Invalid consumer key or secret.',
  NO_AGENT_ERROR: 'Please [1[create an agent]] first to connect your store.',
  NETWORK_ERROR_TITLE: 'Connection issue',
  NETWORK_ERROR_DESC_NETWORK: 'Can’t connect to the server. Please check your internet connection or try again.',
  UNAUTHORIZED_API_KEY_TITLE: 'Unauthorized Access',
  ALMOST_FULL_LIMIT_WARNING_TEXT: 'You’re close to your [1[{limit}]] [2[limit]]. Upgrade to keep your agent active.',
  OVERLIMIT_LIMIT_WARNING_TEXT: 'You’ve reached your [1[{limit}]] [2[limit]]. Upgrade to keep your agent active.',
  UPGRADE_NOW: 'Upgrade Now',
  LOCALHOST_ERROR: 'WooCommerce features can’t be used on a [1[local server.]]',
  SHOW_MORE: 'Show more',
  LOADING: 'Loading...',
  GO_TO_SUPPORT_PAGE: 'Go to support page',
  GET_SUPPORT: 'Get Support',
  CHANGE_IMAGE: 'Change Image',
  SAVE: 'Save',
  CUSTOM_AVATAR: 'Custom Avatar',
  EDIT_AVATAR: 'Edit Avatar',
  CHANGE_AVATAR: 'Change Avatar',
  IMAGE_SIZE: 'Image Size'
};
